/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as AlertEventIdRouteImport } from './routes/alert.$eventId'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as MedicationSubjectIdRouteImport } from './routes/medication.$subjectId'
import { Route as ReportShelterIdRouteImport } from './routes/report.$shelterId'
import { Route as SubjectsIdRouteImport } from './routes/subjects.$id'
import { Route as SubjectsNewRouteImport } from './routes/subjects.new'
import { Route as VerifyUidRouteImport } from './routes/verify.$uid'
import { Route as ApiCronAttestationsRouteImport } from './routes/api.cron.attestations'
import { Route as ApiCronNotificationsRouteImport } from './routes/api.cron.notifications'
import { Route as ApiCronRetentionRouteImport } from './routes/api.cron.retention'
import { Route as ApiCronRiskRouteImport } from './routes/api.cron.risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertEventIdRoute = AlertEventIdRouteImport.update({
  id: '/alert/$eventId',
  path: '/alert/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationSubjectIdRoute = MedicationSubjectIdRouteImport.update({
  id: '/medication/$subjectId',
  path: '/medication/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportShelterIdRoute = ReportShelterIdRouteImport.update({
  id: '/report/$shelterId',
  path: '/report/$shelterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIdRoute = SubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsNewRoute = SubjectsNewRouteImport.update({
  id: '/subjects/new',
  path: '/subjects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyUidRoute = VerifyUidRouteImport.update({
  id: '/verify/$uid',
  path: '/verify/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAttestationsRoute = ApiCronAttestationsRouteImport.update({
  id: '/api/cron/attestations',
  path: '/api/cron/attestations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNotificationsRoute = ApiCronNotificationsRouteImport.update({
  id: '/api/cron/notifications',
  path: '/api/cron/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetentionRoute = ApiCronRetentionRouteImport.update({
  id: '/api/cron/retention',
  path: '/api/cron/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRiskRoute = ApiCronRiskRouteImport.update({
  id: '/api/cron/risk',
  path: '/api/cron/risk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/shelters': typeof SheltersRoute
  '/alert/$eventId': typeof AlertEventIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/medication/$subjectId': typeof MedicationSubjectIdRoute
  '/report/$shelterId': typeof ReportShelterIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects/new': typeof SubjectsNewRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/api/cron/attestations': typeof ApiCronAttestationsRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/risk': typeof ApiCronRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/shelters': typeof SheltersRoute
  '/alert/$eventId': typeof AlertEventIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/medication/$subjectId': typeof MedicationSubjectIdRoute
  '/report/$shelterId': typeof ReportShelterIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects/new': typeof SubjectsNewRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/api/cron/attestations': typeof ApiCronAttestationsRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/risk': typeof ApiCronRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/shelters': typeof SheltersRoute
  '/alert/$eventId': typeof AlertEventIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/medication/$subjectId': typeof MedicationSubjectIdRoute
  '/report/$shelterId': typeof ReportShelterIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects/new': typeof SubjectsNewRoute
  '/verify/$uid': typeof VerifyUidRoute
  '/api/cron/attestations': typeof ApiCronAttestationsRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/risk': typeof ApiCronRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/shelters'
    | '/alert/$eventId'
    | '/dev/components'
    | '/medication/$subjectId'
    | '/report/$shelterId'
    | '/subjects/$id'
    | '/subjects/new'
    | '/verify/$uid'
    | '/api/cron/attestations'
    | '/api/cron/notifications'
    | '/api/cron/retention'
    | '/api/cron/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/shelters'
    | '/alert/$eventId'
    | '/dev/components'
    | '/medication/$subjectId'
    | '/report/$shelterId'
    | '/subjects/$id'
    | '/subjects/new'
    | '/verify/$uid'
    | '/api/cron/attestations'
    | '/api/cron/notifications'
    | '/api/cron/retention'
    | '/api/cron/risk'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/shelters'
    | '/alert/$eventId'
    | '/dev/components'
    | '/medication/$subjectId'
    | '/report/$shelterId'
    | '/subjects/$id'
    | '/subjects/new'
    | '/verify/$uid'
    | '/api/cron/attestations'
    | '/api/cron/notifications'
    | '/api/cron/retention'
    | '/api/cron/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SheltersRoute: typeof SheltersRoute
  AlertEventIdRoute: typeof AlertEventIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  MedicationSubjectIdRoute: typeof MedicationSubjectIdRoute
  ReportShelterIdRoute: typeof ReportShelterIdRoute
  SubjectsIdRoute: typeof SubjectsIdRoute
  SubjectsNewRoute: typeof SubjectsNewRoute
  VerifyUidRoute: typeof VerifyUidRoute
  ApiCronAttestationsRoute: typeof ApiCronAttestationsRoute
  ApiCronNotificationsRoute: typeof ApiCronNotificationsRoute
  ApiCronRetentionRoute: typeof ApiCronRetentionRoute
  ApiCronRiskRoute: typeof ApiCronRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/$eventId': {
      id: '/alert/$eventId'
      path: '/alert/$eventId'
      fullPath: '/alert/$eventId'
      preLoaderRoute: typeof AlertEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication/$subjectId': {
      id: '/medication/$subjectId'
      path: '/medication/$subjectId'
      fullPath: '/medication/$subjectId'
      preLoaderRoute: typeof MedicationSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$shelterId': {
      id: '/report/$shelterId'
      path: '/report/$shelterId'
      fullPath: '/report/$shelterId'
      preLoaderRoute: typeof ReportShelterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$id': {
      id: '/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/subjects/$id'
      preLoaderRoute: typeof SubjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/new': {
      id: '/subjects/new'
      path: '/subjects/new'
      fullPath: '/subjects/new'
      preLoaderRoute: typeof SubjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$uid': {
      id: '/verify/$uid'
      path: '/verify/$uid'
      fullPath: '/verify/$uid'
      preLoaderRoute: typeof VerifyUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/attestations': {
      id: '/api/cron/attestations'
      path: '/api/cron/attestations'
      fullPath: '/api/cron/attestations'
      preLoaderRoute: typeof ApiCronAttestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notifications': {
      id: '/api/cron/notifications'
      path: '/api/cron/notifications'
      fullPath: '/api/cron/notifications'
      preLoaderRoute: typeof ApiCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retention': {
      id: '/api/cron/retention'
      path: '/api/cron/retention'
      fullPath: '/api/cron/retention'
      preLoaderRoute: typeof ApiCronRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/risk': {
      id: '/api/cron/risk'
      path: '/api/cron/risk'
      fullPath: '/api/cron/risk'
      preLoaderRoute: typeof ApiCronRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SheltersRoute: SheltersRoute,
  AlertEventIdRoute: AlertEventIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  MedicationSubjectIdRoute: MedicationSubjectIdRoute,
  ReportShelterIdRoute: ReportShelterIdRoute,
  SubjectsIdRoute: SubjectsIdRoute,
  SubjectsNewRoute: SubjectsNewRoute,
  VerifyUidRoute: VerifyUidRoute,
  ApiCronAttestationsRoute: ApiCronAttestationsRoute,
  ApiCronNotificationsRoute: ApiCronNotificationsRoute,
  ApiCronRetentionRoute: ApiCronRetentionRoute,
  ApiCronRiskRoute: ApiCronRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
